services:
  frontend:
    build: .
    container_name: chat_frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - chat_network

networks:
  chat_network:
    external: true
